### ISSUE TITLE
.gitinginore

### ISSUE THREAD

**Issue by bmarchete** [juliocRamos/laravel-application#1]
@juliocRamos Observa que tem um arquivo chamado .gitignore na pasta do projeto. Como o laravel é cheio de dependências, esse arquivo diz pra o git ignorar todas essas dependencias, e subir apenas o necessário. Quando você fizer o clone desse repo em outra máquina, você vai precisar reinstalar essas dependências. O google pode te ajudar

Se precisar de ajuda, depois do google é claro, me avisa! 😃

**Comment by bmarchete** [comment]
Com certeza! Ele existe justamente pra não ter esse e outros streamings desnecessários!

**Comment by juliocRamos** [comment]
Entendi. Já fiz o teste e aprendi a repor as dependências.
Obrigado Binho

**Comment by bmarchete** [comment]
Quando vc clona, ele não traz o arquivo .env que tem que ser desenvolvido na mao, ou utilizado um exemplo. Além disso, é bom vc executar o comando php artisan key:generate para ele gerar um anova chave de criptografia. Isso tudo depois do composer dump-autoload. 

Se tá tudo entendido já, vc já pode fechar essa issue!

**Comment by juliocRamos** [comment]
@bmarchete  Aqui tem o arquivo .env.example, é só renomear ele para .env?

**Comment by bmarchete** [comment]
Vc pode usar ele, trocar o nome, e colocar as configurações de banco do seu projeto!

**Comment by juliocRamos** [comment]
Beleza, issue encerrada!
